name: github-actions-test

on: [push]
jobs:
  lint-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Lint ascii documents
        run: docker run --platform linux/x86_64 --rm -v $(pwd):/documents ghcr.io/kanameg/textlint-asciidoc:latest textlint 機械学習メモ.adoc