name: github-actions-test

on: [push]
jobs:
  lint-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 
        uses: actions/checkout@v2 # Required to mount the Github Workspace to a volume
      - name: Lint ascii documents
        uses: addnab/docker-run-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
          image: ghcr.io/kanameg/textlint-asciidoc:latest
          options: --platform linux/x86_64 --rm -v ${{ github.workspace }}:/documents
          run: |
            textlint 機械学習メモ.adoc