name: github-actions-test

on: [push]
jobs:
  check-version:
    runs-on: ubuntu-latest
    steps:
      - run: docker run --platform linux/x86_64 --rm -v $(pwd):/documents registry.gitlab.com/kanameg/textlint-asciidoc textlint 機械学習メモ.adoc